### ISSUE TITLE
hal & BIP-Schnorr?

### ISSUE THREAD

**Issue by ChristopherA** [stevenroose/hal#13]
Any thoughts on integrating the latest x-only BIP-Schnoor PR https://github.com/bitcoin-core/secp256k1/pull/558 into some hal tools? @ncklr says it is ready.

I know that I'd like to see soon for file signing [minisign])(https://jedisct1.github.io/minisign/) but with SecP-based Schnorr and maybe optional signtoconttract-like [sighacker](https://github.com/apoelstra/sighacker) signing.

Another tool I'd like to ported to use x-only BIP-Schnorr public keys is minilock for encrypting files (a c-version is at https://gitlab.com/saalen/mikrolock), but the minilock format probably needs some rethinking as you might be able to leverage key aggregation.

-- Christopher Allen

P.S. There is some possible funding for these as paid projects from @BlockchainCommons if you are interested, as we've been receiving bitcoin from Patrons to support open source blockchain projects.

**Comment by stevenroose** [comment]
For this I would be waiting for `rust-secp256k1-zkp` to implement the Schnorr BIP. I think @jonasnick might be working on that already.

**Comment by stevenroose** [comment]
Gonna close this, if you have additional requests regarding Schnorr, feel welcome to open a new issue.
