### ISSUE TITLE
`hal key inspect` should accept a hex privkey

### ISSUE THREAD

**Issue by gwillen** [stevenroose/hal#20]
It would be convenient if `hal key inspect` accepted keys in hex format as well as WIF.

(In general I think hal's "swiss army knife status" means it would be good if _every_ hal command accepts any reasonable format, and can easily convert between them.)

**Comment by stevenroose** [comment]
I agree. Should be added in https://github.com/stevenroose/hal/commit/35aaf174c52c6eda5898714f429346323a19cce3 and v0.7.2 :)

**Comment by gwillen** [comment]
Nice, it works, thanks!

Can you perhaps also enhance `hal key inspect` to print out the WIF format key? (So that it can be used to convert back and forth?) Probably easiest to just do it unconditionally (even if you also entered it that way.)

Other things that would be useful to output / make possible to obtain: The network prefix (coming from WIF) or the WIF for different networks (mainnet vs testnet) when coming from hex. (In fact, I guess when coming from hex you can't print the WIF without knowing or assuming which network it is.)
