### ISSUE TITLE
HAL 0.7.2  .. updated compile?

### ISSUE THREAD

**Issue by mikejnpc** [stevenroose/hal#21]
[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> C:\Users\M\.cargo\registry\src\github.com-1ecc6299db9ec823\lightning-invoice-0.2.0\src\lib.rs:59:11
   |
59 |     unsafe { std::mem::transmute::<SystemTime, [u8; 16]>(UNIX_EPOCH); }
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `SystemTime` (64 bits)
   = note: target type: `[u8; 16]` (128 bits)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0512`.
error: could not compile `lightning-invoice`

error: failed to compile `hal v0.7.2`,

**Comment by stevenroose** [comment]
Hmm, this is probably an issue with an old version of rust or so? Or you discarded the lockfile? I'm gonna close this as it's about an old version of hal.
