### ISSUE TITLE
release latest version on github

### ISSUE THREAD

**Issue by happysalada** [stevenroose/hal#26]
it looks like the latest version 0.8.2 is not a github release.
Just a detail when you have a moment.

Thank you for the great software!

**Comment by stevenroose** [comment]
We don't really do github releases, even though we did that for a few of the versions. All releases are tagged though, so you can get the source for them in the `tags` tab of the releases page: https://github.com/stevenroose/hal/tags.

Does that help you or was there something specific in the releases you were using?

**Comment by happysalada** [comment]
Tags is perfect, thanks !
