### ISSUE TITLE
Show structure of JSON arguments in help

### ISSUE THREAD

**Issue by sgeisler** [stevenroose/hal#5]
`hal tx create -h` only shows `hal tx create [FLAGS] <tx-info>` and `<tx-info>    the transaction info in JSON` as usage documentation which isn't sufficient to use the command. The best option would be to display the JSON schema. But I see that this could be overly complicated and long, so maybe an exhaustive example could be enough for all practical purposes?

**Comment by stevenroose** [comment]
Hmm, good point. It's basically the reverse of `hal tx decode` (with some fields ignored if you provide them).

Related to this, I've been thinking of having a `hal tx decode --minimal` that doesn't print redundant info (like size, txid, etc; just minimal information to reconstruct the tx with `hal tx create`). In that case we might refer to that and then it wouldn't be that hard to provide an example.

Certainly it needs some more information.

**Comment by stevenroose** [comment]
Would https://github.com/stevenroose/hal/pull/6 do?
